// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Used only by the Prisma CLI (migrate/introspect). The app itself connects
  // via the PrismaPg adapter using DATABASE_URL (see src/lib/prisma.ts), which
  // can point at a connection pooler instead.
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
